Simplify downstream integration
PQCMayo/MAYO-C pull request #4
Opened 2024-05-09 09:55 UTC by bhess

- adds META.yml files
- adds new api: crypto_sign_signature and crypto_sign_verify
- adds namespacing
- converts CRLF to LF
- fixes for big-endian
- changes types from 'unsigned long long' to size_t
- fixes for strict compilers
- ensures newlines at end of files

2024-05-10 07:13 UTC, mkannwischer requested changes
Thanks @bhess for the integration into liboqs - that's going to be very useful for many people. The changes look mostly good to me. 

Tested this PR downstream in https://github.com/PQCMayo/MAYO-M4. 
It only requires some minor changes: https://github.com/PQCMayo/MAYO-M4/tree/liboqs-integration

Since you changed to `size_t`, you can remove the cases in the `api.c`

2024-05-10 07:13 UTC, mkannwischer commented on src/mayo_1/api.c
>  #ifndef PQM4
I think this is no longer needed if you change to `size_t` everywhere.

2024-05-10 07:13 UTC, mkannwischer commented on src/mayo_1/api.c
>  #ifndef PQM4
Tested it. Yes, you can simply remove the #else part

2024-05-12 08:07 UTC, bhess commented
Thanks @mkannwischer, I removed the PQM4 cases from api.c/.h.

2024-05-12 08:07 UTC, merged